// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3otPlcxbvbz40wPL89deaaTcLFyC2S_Q',
    appId: '1:122685023944:web:faf89a283f9dbc49b027fd',
    messagingSenderId: '122685023944',
    projectId: 'hope-57790',
    authDomain: 'hope-57790.firebaseapp.com',
    storageBucket: 'hope-57790.appspot.com',
    measurementId: 'G-LM2EBBFGYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbWy2CX7B7BR6A9GgiQOx_UhxccWHOus',
    appId: '1:122685023944:android:455cfb420640d68cb027fd',
    messagingSenderId: '122685023944',
    projectId: 'hope-57790',
    storageBucket: 'hope-57790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-EYoxkjaR6i58jRhn3R36IGrTzW96FLM',
    appId: '1:122685023944:ios:f223a7cb19c71076b027fd',
    messagingSenderId: '122685023944',
    projectId: 'hope-57790',
    storageBucket: 'hope-57790.appspot.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-EYoxkjaR6i58jRhn3R36IGrTzW96FLM',
    appId: '1:122685023944:ios:f223a7cb19c71076b027fd',
    messagingSenderId: '122685023944',
    projectId: 'hope-57790',
    storageBucket: 'hope-57790.appspot.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3otPlcxbvbz40wPL89deaaTcLFyC2S_Q',
    appId: '1:122685023944:web:7c965ef0c9c0a16bb027fd',
    messagingSenderId: '122685023944',
    projectId: 'hope-57790',
    authDomain: 'hope-57790.firebaseapp.com',
    storageBucket: 'hope-57790.appspot.com',
    measurementId: 'G-36CH1ZD9NR',
  );
}
